### ISSUE TITLE
Stocker l'instance d'un objet plutôt que ses attributs de manière séparée

### ISSUE THREAD

**Issue by jplumez** [melissavoirol/MovieManager#26]
Dans PersonDetailBean, pourquoi stocker les attributs de la personne de manière séparée ? Ca n'apporte rien et c'est beaucoup trop "compliqué" ! Il suffit de stocker l'instance de la personne, et dans les pages vous faites personDetailBean.person.firstName (comme dans MovieDetailsBean !)

**Comment by Kboris20** [comment]
Fait et sera committé au même moment que les issues #22, #23 #24
